name: Kubernetes CI/CD (No SSH)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t portfolio .

      - name: Create Kind cluster
        uses: helm/kind-action@v1

      - name: Load image into Kind
        run: kind load docker-image portfolio

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/
